# Generated by Django 2.1.5 on 2019-01-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_college_website'),
        ('educourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educourse',
            name='university',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='institute.University'),
            preserve_default=False,
        ),
    ]
