# Generated by Django 2.1.5 on 2019-01-21 12:45

from django.db import migrations, models
import django.db.models.deletion
import educourse.models


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0002_educourse_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('code', models.CharField(max_length=5)),
                ('study_year', models.CharField(blank=True, choices=[('First Year(1st)', 'First Year(1st)'), ('Second Year(2nd)', 'Second Year(2nd)'), ('Third Year(3rd)', 'Third Year(3rd)')], default='Not Selected', max_length=255)),
                ('syllabus', models.FileField(blank=True, upload_to=educourse.models.upload_file_path)),
                ('max_marks', models.IntegerField()),
                ('min_marks', models.IntegerField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='educourse.EduCourse')),
            ],
        ),
    ]
