# Generated by Django 2.1.5 on 2019-01-21 13:05

from django.db import migrations, models
import django.db.models.deletion
import educourse.models


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0003_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuetionP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('exam_year', models.IntegerField()),
                ('exam_time', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], default='Not Selected', max_length=255)),
                ('file', models.FileField(blank=True, upload_to=educourse.models.upload_file_path)),
                ('max_marks', models.IntegerField()),
                ('min_marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='study_year',
            field=models.CharField(choices=[('First Year(1st)', 'First Year(1st)'), ('Second Year(2nd)', 'Second Year(2nd)'), ('Third Year(3rd)', 'Third Year(3rd)')], default='Not Selected', max_length=255),
        ),
        migrations.AddField(
            model_name='quetionp',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='educourse.Subject'),
        ),
    ]
