# Generated by Django 2.1.5 on 2019-01-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0004_auto_20190121_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuetionP',
            new_name='QuetionPaper',
        ),
    ]
