# Generated by Django 2.1.5 on 2019-01-21 13:58

from django.db import migrations, models
import django.db.models.deletion
import educourse.models


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0005_auto_20190121_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAnswerPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('exam_year', models.IntegerField()),
                ('exam_time', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], default='Not Selected', max_length=255)),
                ('file', models.FileField(blank=True, upload_to=educourse.models.upload_file_path)),
                ('max_marks', models.IntegerField()),
                ('min_marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='educourse.Subject')),
            ],
        ),
    ]
