# Generated by Django 2.1.5 on 2019-01-23 14:38

from django.db import migrations, models
import educourse.models


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0006_modelanswerpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelanswerpaper',
            name='scheme',
            field=models.CharField(choices=[('E', 'E'), ('G', 'G'), ('I', 'I'), ('M', 'M')], default='Not Selected', max_length=255),
        ),
        migrations.AddField(
            model_name='quetionpaper',
            name='scheme',
            field=models.CharField(choices=[('E', 'E'), ('G', 'G'), ('I', 'I'), ('M', 'M')], default='Not Selected', max_length=255),
        ),
        migrations.AddField(
            model_name='subject',
            name='curriculam',
            field=models.FileField(blank=True, upload_to=educourse.models.upload_file_path),
        ),
    ]
