# Generated by Django 2.1.5 on 2019-01-23 14:44

from django.db import migrations, models
import django.db.models.deletion
import educourse.models


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0007_auto_20190123_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('scheme', models.CharField(choices=[('E', 'E'), ('G', 'G'), ('I', 'I'), ('M', 'M')], default='Not Selected', max_length=255)),
                ('file', models.FileField(blank=True, upload_to=educourse.models.upload_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='curriculam',
        ),
        migrations.AddField(
            model_name='curriculam',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='educourse.Subject'),
        ),
    ]
