# Generated by Django 2.1.5 on 2019-01-23 14:46

from django.db import migrations, models
import educourse.models


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0008_auto_20190123_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculam',
            name='file',
            field=models.FileField(upload_to=educourse.models.upload_file_path),
        ),
    ]
