# Generated by Django 2.1.5 on 2019-01-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0010_auto_20190124_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educourse',
            name='scheme',
        ),
    ]
