# Generated by Django 2.1.5 on 2019-01-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0011_remove_educourse_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educourse.Subject'),
        ),
    ]
