# Generated by Django 2.1.5 on 2019-01-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0013_auto_20190124_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='min_marks',
        ),
        migrations.AlterField(
            model_name='modelanswerpaper',
            name='max_marks',
            field=models.IntegerField(default=100, null=None),
        ),
        migrations.AlterField(
            model_name='modelanswerpaper',
            name='min_marks',
            field=models.IntegerField(default=40, null=None),
        ),
        migrations.AlterField(
            model_name='quetionpaper',
            name='max_marks',
            field=models.IntegerField(default=100, null=None),
        ),
        migrations.AlterField(
            model_name='quetionpaper',
            name='min_marks',
            field=models.IntegerField(default=40, null=None),
        ),
    ]
