# Generated by Django 2.1.5 on 2019-01-24 07:56

from django.db import migrations, models
import educourse.models
import educourse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0014_auto_20190124_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanswerpaper',
            name='file',
            field=models.FileField(upload_to=educourse.models.upload_file_path, validators=[educourse.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='quetionpaper',
            name='file',
            field=models.FileField(upload_to=educourse.models.upload_file_path, validators=[educourse.validators.validate_file_extension]),
        ),
    ]
