# Generated by Django 2.1.5 on 2019-01-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educourse', '0015_auto_20190124_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educourse',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.University'),
        ),
        migrations.AlterField(
            model_name='modelanswerpaper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educourse.Subject'),
        ),
        migrations.AlterField(
            model_name='quetionpaper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educourse.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educourse.EduCourse'),
        ),
    ]
