# Generated by Django 2.1.5 on 2019-01-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=5)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('Reporting Problem', 'Reporting Problem'), ('Feedback', 'Feedback'), ('Not Specific', 'Not Specific')], default='Not Selected', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
