# Generated by Django 2.1.5 on 2019-01-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
