# Generated by Django 2.1.5 on 2019-01-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
