# Generated by Django 2.1.5 on 2019-01-10 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20190110_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Completed'), (2, 'Persuing')], null=True)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
