# Generated by Django 2.1.5 on 2019-01-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190112_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/uploads/user.png', upload_to='uploads/%y/%m/%d/'),
        ),
    ]
