# Generated by Django 2.1.5 on 2019-01-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='type',
            field=models.CharField(default='ddsweb.in', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(default='ddsweb.in'),
            preserve_default=False,
        ),
    ]
