# Generated by Django 2.1.5 on 2019-01-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20190121_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.URLField(default='dstudy.ddsweb.in'),
        ),
    ]
