# Generated by Django 2.1.5 on 2019-01-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_auto_20190125_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='contact2',
            field=models.BigIntegerField(default='9421487587'),
        ),
    ]
