# Generated by Django 2.1.5 on 2019-01-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_college_contact2'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='email',
            field=models.EmailField(default='ddsi.dstudy@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='university',
            name='fax',
            field=models.BigIntegerField(default='0000000000'),
        ),
        migrations.AddField(
            model_name='university',
            name='phone',
            field=models.BigIntegerField(default='9421487587'),
        ),
    ]
